export type Student = {
    _id?: string
    fullName: string
    fatherName: string
    fatherCnic?: string
    dob: string
    rollNumber: string
    grNumber: string
    gender: string
    admissionFor: string
    nationality: string
    medicalCondition: string
    cnicOrBform: string
    email?: string
    phoneNumber?: string
    whatsappNumber?: string
    address?: string
    formerEducation?: string
    previousInstitute?: string
    lastExamPercentage?: string
    guardianName?: string
    guardianContact?: string
    guardianCnic?: string
    guardianRelation?: string
    photoUrl?: string
    issueDate?: string
    expiryDate?: string
    session?: string
}